//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assesment_Week2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Account_Number { get; set; }
        public string Owner_Name { get; set; }
        public Nullable<float> Balance { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
